# Generated by Django 5.0 on 2024-01-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0002_genome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genome',
        ),
    ]
